SDKVERSION = 7.0
ARCHS = armv7 arm64

include theos/makefiles/common.mk

TWEAK_NAME = DictationToggle
DictationToggle_FILES = Tweak.xm
DictationToggle_PRIVATE_FRAMEWORKS = AssistantServices

include $(THEOS_MAKE_PATH)/tweak.mk


